# server config
server:
  port: 8080
  servlet:
    context-path: /hello
    session:
      timeout: PT2H
      
# spring config      
spring:
  session:    store-type: redis
  redis:    host: 127.0.0.1
    port: 6379
    lettuce:      pool:        min-idle: 1
        max-idle: 10
        max-active: 200
        max-wait: 2000
#    jedis:#      pool:#        min-idle: 0
#        max-idle: 10
#        max-active: 200
#        max-wait: 2000  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    # druid config
    druid:      url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 10000
      max-create-task-count: 10
      stat-view-servlet:
        enabled: true        url-pattern: /druid/*
        login-username: admin
        login-password: admin123
        
  # freemarker config  freemarker:
    enabled: true    charset: UTF-8
    suffix: .html
    check-template-location: true
    template-loader-path:    - classpath:/templates/
    
# mybatis
mybatis:  mapper-locations:  - classpath:mapper/**/*.xml
  
# logback
logging:  config: classpath:logback.xml
  
      