package com.tan.start.dao;

import com.tan.start.entity.CourseInfo;
import com.tan.start.entity.CourseInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    long countByExample(CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    int deleteByExample(CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    int insert(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    int insertSelective(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    List<CourseInfo> selectByExample(CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    CourseInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") CourseInfo record, @Param("example") CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    int updateByExample(@Param("record") CourseInfo record, @Param("example") CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    int updateByPrimaryKeySelective(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    int updateByPrimaryKey(CourseInfo record);
}