package com.tan.start.dao;

import com.tan.start.entity.FundData;
import com.tan.start.entity.FundDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    long countByExample(FundDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int deleteByExample(FundDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int deleteByPrimaryKey(String tsCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int insert(FundData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int insertSelective(FundData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    List<FundData> selectByExampleWithBLOBs(FundDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    List<FundData> selectByExample(FundDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    FundData selectByPrimaryKey(String tsCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") FundData record, @Param("example") FundDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") FundData record, @Param("example") FundDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int updateByExample(@Param("record") FundData record, @Param("example") FundDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int updateByPrimaryKeySelective(FundData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(FundData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int updateByPrimaryKey(FundData record);
}