package com.tan.start.dao;

import com.tan.start.entity.SuccessRecord;
import com.tan.start.entity.SuccessRecordExample;
import com.tan.start.entity.SuccessRecordKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuccessRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_record
     *
     * @mbg.generated Sat Mar 30 10:10:08 CST 2019
     */
    long countByExample(SuccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_record
     *
     * @mbg.generated Sat Mar 30 10:10:08 CST 2019
     */
    int deleteByExample(SuccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_record
     *
     * @mbg.generated Sat Mar 30 10:10:08 CST 2019
     */
    int deleteByPrimaryKey(SuccessRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_record
     *
     * @mbg.generated Sat Mar 30 10:10:08 CST 2019
     */
    int insert(SuccessRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_record
     *
     * @mbg.generated Sat Mar 30 10:10:08 CST 2019
     */
    int insertSelective(SuccessRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_record
     *
     * @mbg.generated Sat Mar 30 10:10:08 CST 2019
     */
    List<SuccessRecord> selectByExample(SuccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_record
     *
     * @mbg.generated Sat Mar 30 10:10:08 CST 2019
     */
    SuccessRecord selectByPrimaryKey(SuccessRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_record
     *
     * @mbg.generated Sat Mar 30 10:10:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") SuccessRecord record, @Param("example") SuccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_record
     *
     * @mbg.generated Sat Mar 30 10:10:08 CST 2019
     */
    int updateByExample(@Param("record") SuccessRecord record, @Param("example") SuccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_record
     *
     * @mbg.generated Sat Mar 30 10:10:08 CST 2019
     */
    int updateByPrimaryKeySelective(SuccessRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_record
     *
     * @mbg.generated Sat Mar 30 10:10:08 CST 2019
     */
    int updateByPrimaryKey(SuccessRecord record);
}