package com.tan.start.dao;

import com.tan.start.entity.SysOrganization;
import com.tan.start.entity.SysOrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    long countByExample(SysOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int deleteByExample(SysOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int insert(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int insertSelective(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    List<SysOrganization> selectByExample(SysOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    SysOrganization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysOrganization record, @Param("example") SysOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int updateByExample(@Param("record") SysOrganization record, @Param("example") SysOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int updateByPrimaryKeySelective(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    int updateByPrimaryKey(SysOrganization record);
}