package com.tan.start.dao;

import com.tan.start.entity.SysPermissionGroup;
import com.tan.start.entity.SysPermissionGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysPermissionGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Thu Jul 04 16:06:26 CST 2019
     */
    long countByExample(SysPermissionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Thu Jul 04 16:06:26 CST 2019
     */
    int deleteByExample(SysPermissionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Thu Jul 04 16:06:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Thu Jul 04 16:06:26 CST 2019
     */
    int insert(SysPermissionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Thu Jul 04 16:06:26 CST 2019
     */
    int insertSelective(SysPermissionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Thu Jul 04 16:06:26 CST 2019
     */
    List<SysPermissionGroup> selectByExample(SysPermissionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Thu Jul 04 16:06:26 CST 2019
     */
    SysPermissionGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Thu Jul 04 16:06:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysPermissionGroup record, @Param("example") SysPermissionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Thu Jul 04 16:06:26 CST 2019
     */
    int updateByExample(@Param("record") SysPermissionGroup record, @Param("example") SysPermissionGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Thu Jul 04 16:06:26 CST 2019
     */
    int updateByPrimaryKeySelective(SysPermissionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Thu Jul 04 16:06:26 CST 2019
     */
    int updateByPrimaryKey(SysPermissionGroup record);
}