package com.tan.start.dao;

import com.tan.start.entity.SysPermissionResource;
import com.tan.start.entity.SysPermissionResourceExample;
import com.tan.start.entity.SysPermissionResourceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysPermissionResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resource
     *
     * @mbg.generated Thu Jul 11 16:22:36 CST 2019
     */
    long countByExample(SysPermissionResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resource
     *
     * @mbg.generated Thu Jul 11 16:22:36 CST 2019
     */
    int deleteByExample(SysPermissionResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resource
     *
     * @mbg.generated Thu Jul 11 16:22:36 CST 2019
     */
    int deleteByPrimaryKey(SysPermissionResourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resource
     *
     * @mbg.generated Thu Jul 11 16:22:36 CST 2019
     */
    int insert(SysPermissionResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resource
     *
     * @mbg.generated Thu Jul 11 16:22:36 CST 2019
     */
    int insertSelective(SysPermissionResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resource
     *
     * @mbg.generated Thu Jul 11 16:22:36 CST 2019
     */
    List<SysPermissionResource> selectByExample(SysPermissionResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resource
     *
     * @mbg.generated Thu Jul 11 16:22:36 CST 2019
     */
    SysPermissionResource selectByPrimaryKey(SysPermissionResourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resource
     *
     * @mbg.generated Thu Jul 11 16:22:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysPermissionResource record, @Param("example") SysPermissionResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resource
     *
     * @mbg.generated Thu Jul 11 16:22:36 CST 2019
     */
    int updateByExample(@Param("record") SysPermissionResource record, @Param("example") SysPermissionResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resource
     *
     * @mbg.generated Thu Jul 11 16:22:36 CST 2019
     */
    int updateByPrimaryKeySelective(SysPermissionResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resource
     *
     * @mbg.generated Thu Jul 11 16:22:36 CST 2019
     */
    int updateByPrimaryKey(SysPermissionResource record);
}