package com.tan.start.dao;

import com.tan.start.entity.SysPermissionGroups;
import com.tan.start.entity.SysPermissionGroupsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysPermissionGroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    long countByExample(SysPermissionGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int deleteByExample(SysPermissionGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int insert(SysPermissionGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int insertSelective(SysPermissionGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    List<SysPermissionGroups> selectByExample(SysPermissionGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    SysPermissionGroups selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysPermissionGroups record, @Param("example") SysPermissionGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int updateByExample(@Param("record") SysPermissionGroups record, @Param("example") SysPermissionGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int updateByPrimaryKeySelective(SysPermissionGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int updateByPrimaryKey(SysPermissionGroups record);
}