package com.tan.start.dao;

import com.tan.start.dto.RoleResourceDTO;
import com.tan.start.dto.SysResourceDTO;
import com.tan.start.entity.SysResource;
import com.tan.start.entity.SysResourceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    long countByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int deleteByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int insertSelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    List<SysResourceDTO> selectByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    SysResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysResource record, @Param("example") SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int updateByExample(@Param("record") SysResource record, @Param("example") SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int updateByPrimaryKeySelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int updateByPrimaryKey(SysResource record);

    List<RoleResourceDTO> selectSysResourceByRoleId(@Param("example")SysResourceExample example, @Param("roleId")Integer roleId, @Param("available") Boolean available);
}