package com.tan.start.dao;

import com.tan.start.entity.SysRoleResource;
import com.tan.start.entity.SysRoleResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sat Jul 06 16:00:59 CST 2019
     */
    long countByExample(SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sat Jul 06 16:00:59 CST 2019
     */
    int deleteByExample(SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sat Jul 06 16:00:59 CST 2019
     */
    int insert(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sat Jul 06 16:00:59 CST 2019
     */
    int insertSelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sat Jul 06 16:00:59 CST 2019
     */
    List<SysRoleResource> selectByExample(SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sat Jul 06 16:00:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysRoleResource record, @Param("example") SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sat Jul 06 16:00:59 CST 2019
     */
    int updateByExample(@Param("record") SysRoleResource record, @Param("example") SysRoleResourceExample example);
}