package com.tan.start.dao;

import com.tan.start.entity.SysRoleResource;
import com.tan.start.entity.SysRoleResourceExample;
import com.tan.start.entity.SysRoleResourceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    long countByExample(SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int deleteByExample(SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int deleteByPrimaryKey(SysRoleResourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int insert(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int insertSelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    List<SysRoleResource> selectByExample(SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    SysRoleResource selectByPrimaryKey(SysRoleResourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysRoleResource record, @Param("example") SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int updateByExample(@Param("record") SysRoleResource record, @Param("example") SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int updateByPrimaryKeySelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated Sun Jul 14 13:05:19 CST 2019
     */
    int updateByPrimaryKey(SysRoleResource record);
}