package com.tan.start.dao;

import com.tan.start.entity.SysUserPermission;
import com.tan.start.entity.SysUserPermissionExample;
import com.tan.start.entity.SysUserPermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    long countByExample(SysUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int deleteByExample(SysUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int deleteByPrimaryKey(SysUserPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int insert(SysUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int insertSelective(SysUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    List<SysUserPermission> selectByExample(SysUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    SysUserPermission selectByPrimaryKey(SysUserPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysUserPermission record, @Param("example") SysUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int updateByExample(@Param("record") SysUserPermission record, @Param("example") SysUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int updateByPrimaryKeySelective(SysUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    int updateByPrimaryKey(SysUserPermission record);
}