package com.tan.start.entity;

public class CourseInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.id
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.cname
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.caddress
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    private String caddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.id
     *
     * @return the value of course_info.id
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.id
     *
     * @param id the value for course_info.id
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.cname
     *
     * @return the value of course_info.cname
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.cname
     *
     * @param cname the value for course_info.cname
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.caddress
     *
     * @return the value of course_info.caddress
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public String getCaddress() {
        return caddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.caddress
     *
     * @param caddress the value for course_info.caddress
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public void setCaddress(String caddress) {
        this.caddress = caddress;
    }
}