package com.tan.start.entity;

import java.io.Serializable;

public class FundData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.ts_code
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String tsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.name
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.management
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String management;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.custodian
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String custodian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.fund_type
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String fundType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.found_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String foundDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.due_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.list_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String listDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.issue_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String issueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.delist_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String delistDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.issue_amount
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private Double issueAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.m_fee
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private Double mFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.c_fee
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private Double cFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.duration_year
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private Double durationYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.p_value
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private Double pValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.min_amount
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private Double minAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.exp_return
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String expReturn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.status
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.invest_type
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String investType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.type
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.trustee
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String trustee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.purc_startdate
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String purcStartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.redm_startdate
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String redmStartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.market
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_data.benchmark
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private String benchmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_data
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.ts_code
     *
     * @return the value of fund_data.ts_code
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.ts_code
     *
     * @param tsCode the value for fund_data.ts_code
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.name
     *
     * @return the value of fund_data.name
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.name
     *
     * @param name the value for fund_data.name
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.management
     *
     * @return the value of fund_data.management
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getManagement() {
        return management;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.management
     *
     * @param management the value for fund_data.management
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setManagement(String management) {
        this.management = management;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.custodian
     *
     * @return the value of fund_data.custodian
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getCustodian() {
        return custodian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.custodian
     *
     * @param custodian the value for fund_data.custodian
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setCustodian(String custodian) {
        this.custodian = custodian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.fund_type
     *
     * @return the value of fund_data.fund_type
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getFundType() {
        return fundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.fund_type
     *
     * @param fundType the value for fund_data.fund_type
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setFundType(String fundType) {
        this.fundType = fundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.found_date
     *
     * @return the value of fund_data.found_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getFoundDate() {
        return foundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.found_date
     *
     * @param foundDate the value for fund_data.found_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setFoundDate(String foundDate) {
        this.foundDate = foundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.due_date
     *
     * @return the value of fund_data.due_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.due_date
     *
     * @param dueDate the value for fund_data.due_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.list_date
     *
     * @return the value of fund_data.list_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getListDate() {
        return listDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.list_date
     *
     * @param listDate the value for fund_data.list_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setListDate(String listDate) {
        this.listDate = listDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.issue_date
     *
     * @return the value of fund_data.issue_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getIssueDate() {
        return issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.issue_date
     *
     * @param issueDate the value for fund_data.issue_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setIssueDate(String issueDate) {
        this.issueDate = issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.delist_date
     *
     * @return the value of fund_data.delist_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getDelistDate() {
        return delistDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.delist_date
     *
     * @param delistDate the value for fund_data.delist_date
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setDelistDate(String delistDate) {
        this.delistDate = delistDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.issue_amount
     *
     * @return the value of fund_data.issue_amount
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public Double getIssueAmount() {
        return issueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.issue_amount
     *
     * @param issueAmount the value for fund_data.issue_amount
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setIssueAmount(Double issueAmount) {
        this.issueAmount = issueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.m_fee
     *
     * @return the value of fund_data.m_fee
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public Double getmFee() {
        return mFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.m_fee
     *
     * @param mFee the value for fund_data.m_fee
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setmFee(Double mFee) {
        this.mFee = mFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.c_fee
     *
     * @return the value of fund_data.c_fee
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public Double getcFee() {
        return cFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.c_fee
     *
     * @param cFee the value for fund_data.c_fee
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setcFee(Double cFee) {
        this.cFee = cFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.duration_year
     *
     * @return the value of fund_data.duration_year
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public Double getDurationYear() {
        return durationYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.duration_year
     *
     * @param durationYear the value for fund_data.duration_year
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setDurationYear(Double durationYear) {
        this.durationYear = durationYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.p_value
     *
     * @return the value of fund_data.p_value
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public Double getpValue() {
        return pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.p_value
     *
     * @param pValue the value for fund_data.p_value
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setpValue(Double pValue) {
        this.pValue = pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.min_amount
     *
     * @return the value of fund_data.min_amount
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public Double getMinAmount() {
        return minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.min_amount
     *
     * @param minAmount the value for fund_data.min_amount
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setMinAmount(Double minAmount) {
        this.minAmount = minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.exp_return
     *
     * @return the value of fund_data.exp_return
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getExpReturn() {
        return expReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.exp_return
     *
     * @param expReturn the value for fund_data.exp_return
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setExpReturn(String expReturn) {
        this.expReturn = expReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.status
     *
     * @return the value of fund_data.status
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.status
     *
     * @param status the value for fund_data.status
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.invest_type
     *
     * @return the value of fund_data.invest_type
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getInvestType() {
        return investType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.invest_type
     *
     * @param investType the value for fund_data.invest_type
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setInvestType(String investType) {
        this.investType = investType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.type
     *
     * @return the value of fund_data.type
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.type
     *
     * @param type the value for fund_data.type
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.trustee
     *
     * @return the value of fund_data.trustee
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getTrustee() {
        return trustee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.trustee
     *
     * @param trustee the value for fund_data.trustee
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setTrustee(String trustee) {
        this.trustee = trustee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.purc_startdate
     *
     * @return the value of fund_data.purc_startdate
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getPurcStartdate() {
        return purcStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.purc_startdate
     *
     * @param purcStartdate the value for fund_data.purc_startdate
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setPurcStartdate(String purcStartdate) {
        this.purcStartdate = purcStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.redm_startdate
     *
     * @return the value of fund_data.redm_startdate
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getRedmStartdate() {
        return redmStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.redm_startdate
     *
     * @param redmStartdate the value for fund_data.redm_startdate
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setRedmStartdate(String redmStartdate) {
        this.redmStartdate = redmStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.market
     *
     * @return the value of fund_data.market
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.market
     *
     * @param market the value for fund_data.market
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setMarket(String market) {
        this.market = market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_data.benchmark
     *
     * @return the value of fund_data.benchmark
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public String getBenchmark() {
        return benchmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_data.benchmark
     *
     * @param benchmark the value for fund_data.benchmark
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    public void setBenchmark(String benchmark) {
        this.benchmark = benchmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tsCode=").append(tsCode);
        sb.append(", name=").append(name);
        sb.append(", management=").append(management);
        sb.append(", custodian=").append(custodian);
        sb.append(", fundType=").append(fundType);
        sb.append(", foundDate=").append(foundDate);
        sb.append(", dueDate=").append(dueDate);
        sb.append(", listDate=").append(listDate);
        sb.append(", issueDate=").append(issueDate);
        sb.append(", delistDate=").append(delistDate);
        sb.append(", issueAmount=").append(issueAmount);
        sb.append(", mFee=").append(mFee);
        sb.append(", cFee=").append(cFee);
        sb.append(", durationYear=").append(durationYear);
        sb.append(", pValue=").append(pValue);
        sb.append(", minAmount=").append(minAmount);
        sb.append(", expReturn=").append(expReturn);
        sb.append(", status=").append(status);
        sb.append(", investType=").append(investType);
        sb.append(", type=").append(type);
        sb.append(", trustee=").append(trustee);
        sb.append(", purcStartdate=").append(purcStartdate);
        sb.append(", redmStartdate=").append(redmStartdate);
        sb.append(", market=").append(market);
        sb.append(", benchmark=").append(benchmark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FundData other = (FundData) that;
        return (this.getTsCode() == null ? other.getTsCode() == null : this.getTsCode().equals(other.getTsCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getManagement() == null ? other.getManagement() == null : this.getManagement().equals(other.getManagement()))
            && (this.getCustodian() == null ? other.getCustodian() == null : this.getCustodian().equals(other.getCustodian()))
            && (this.getFundType() == null ? other.getFundType() == null : this.getFundType().equals(other.getFundType()))
            && (this.getFoundDate() == null ? other.getFoundDate() == null : this.getFoundDate().equals(other.getFoundDate()))
            && (this.getDueDate() == null ? other.getDueDate() == null : this.getDueDate().equals(other.getDueDate()))
            && (this.getListDate() == null ? other.getListDate() == null : this.getListDate().equals(other.getListDate()))
            && (this.getIssueDate() == null ? other.getIssueDate() == null : this.getIssueDate().equals(other.getIssueDate()))
            && (this.getDelistDate() == null ? other.getDelistDate() == null : this.getDelistDate().equals(other.getDelistDate()))
            && (this.getIssueAmount() == null ? other.getIssueAmount() == null : this.getIssueAmount().equals(other.getIssueAmount()))
            && (this.getmFee() == null ? other.getmFee() == null : this.getmFee().equals(other.getmFee()))
            && (this.getcFee() == null ? other.getcFee() == null : this.getcFee().equals(other.getcFee()))
            && (this.getDurationYear() == null ? other.getDurationYear() == null : this.getDurationYear().equals(other.getDurationYear()))
            && (this.getpValue() == null ? other.getpValue() == null : this.getpValue().equals(other.getpValue()))
            && (this.getMinAmount() == null ? other.getMinAmount() == null : this.getMinAmount().equals(other.getMinAmount()))
            && (this.getExpReturn() == null ? other.getExpReturn() == null : this.getExpReturn().equals(other.getExpReturn()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getInvestType() == null ? other.getInvestType() == null : this.getInvestType().equals(other.getInvestType()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getTrustee() == null ? other.getTrustee() == null : this.getTrustee().equals(other.getTrustee()))
            && (this.getPurcStartdate() == null ? other.getPurcStartdate() == null : this.getPurcStartdate().equals(other.getPurcStartdate()))
            && (this.getRedmStartdate() == null ? other.getRedmStartdate() == null : this.getRedmStartdate().equals(other.getRedmStartdate()))
            && (this.getMarket() == null ? other.getMarket() == null : this.getMarket().equals(other.getMarket()))
            && (this.getBenchmark() == null ? other.getBenchmark() == null : this.getBenchmark().equals(other.getBenchmark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Wed Jul 10 15:39:32 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTsCode() == null) ? 0 : getTsCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getManagement() == null) ? 0 : getManagement().hashCode());
        result = prime * result + ((getCustodian() == null) ? 0 : getCustodian().hashCode());
        result = prime * result + ((getFundType() == null) ? 0 : getFundType().hashCode());
        result = prime * result + ((getFoundDate() == null) ? 0 : getFoundDate().hashCode());
        result = prime * result + ((getDueDate() == null) ? 0 : getDueDate().hashCode());
        result = prime * result + ((getListDate() == null) ? 0 : getListDate().hashCode());
        result = prime * result + ((getIssueDate() == null) ? 0 : getIssueDate().hashCode());
        result = prime * result + ((getDelistDate() == null) ? 0 : getDelistDate().hashCode());
        result = prime * result + ((getIssueAmount() == null) ? 0 : getIssueAmount().hashCode());
        result = prime * result + ((getmFee() == null) ? 0 : getmFee().hashCode());
        result = prime * result + ((getcFee() == null) ? 0 : getcFee().hashCode());
        result = prime * result + ((getDurationYear() == null) ? 0 : getDurationYear().hashCode());
        result = prime * result + ((getpValue() == null) ? 0 : getpValue().hashCode());
        result = prime * result + ((getMinAmount() == null) ? 0 : getMinAmount().hashCode());
        result = prime * result + ((getExpReturn() == null) ? 0 : getExpReturn().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getInvestType() == null) ? 0 : getInvestType().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getTrustee() == null) ? 0 : getTrustee().hashCode());
        result = prime * result + ((getPurcStartdate() == null) ? 0 : getPurcStartdate().hashCode());
        result = prime * result + ((getRedmStartdate() == null) ? 0 : getRedmStartdate().hashCode());
        result = prime * result + ((getMarket() == null) ? 0 : getMarket().hashCode());
        result = prime * result + ((getBenchmark() == null) ? 0 : getBenchmark().hashCode());
        return result;
    }
}