package com.tan.start.entity;

import java.util.ArrayList;
import java.util.List;

public class FundDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    public FundDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTsCodeIsNull() {
            addCriterion("ts_code is null");
            return (Criteria) this;
        }

        public Criteria andTsCodeIsNotNull() {
            addCriterion("ts_code is not null");
            return (Criteria) this;
        }

        public Criteria andTsCodeEqualTo(String value) {
            addCriterion("ts_code =", value, "tsCode");
            return (Criteria) this;
        }

        public Criteria andTsCodeNotEqualTo(String value) {
            addCriterion("ts_code <>", value, "tsCode");
            return (Criteria) this;
        }

        public Criteria andTsCodeGreaterThan(String value) {
            addCriterion("ts_code >", value, "tsCode");
            return (Criteria) this;
        }

        public Criteria andTsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ts_code >=", value, "tsCode");
            return (Criteria) this;
        }

        public Criteria andTsCodeLessThan(String value) {
            addCriterion("ts_code <", value, "tsCode");
            return (Criteria) this;
        }

        public Criteria andTsCodeLessThanOrEqualTo(String value) {
            addCriterion("ts_code <=", value, "tsCode");
            return (Criteria) this;
        }

        public Criteria andTsCodeLike(String value) {
            addCriterion("ts_code like", value, "tsCode");
            return (Criteria) this;
        }

        public Criteria andTsCodeNotLike(String value) {
            addCriterion("ts_code not like", value, "tsCode");
            return (Criteria) this;
        }

        public Criteria andTsCodeIn(List<String> values) {
            addCriterion("ts_code in", values, "tsCode");
            return (Criteria) this;
        }

        public Criteria andTsCodeNotIn(List<String> values) {
            addCriterion("ts_code not in", values, "tsCode");
            return (Criteria) this;
        }

        public Criteria andTsCodeBetween(String value1, String value2) {
            addCriterion("ts_code between", value1, value2, "tsCode");
            return (Criteria) this;
        }

        public Criteria andTsCodeNotBetween(String value1, String value2) {
            addCriterion("ts_code not between", value1, value2, "tsCode");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andManagementIsNull() {
            addCriterion("management is null");
            return (Criteria) this;
        }

        public Criteria andManagementIsNotNull() {
            addCriterion("management is not null");
            return (Criteria) this;
        }

        public Criteria andManagementEqualTo(String value) {
            addCriterion("management =", value, "management");
            return (Criteria) this;
        }

        public Criteria andManagementNotEqualTo(String value) {
            addCriterion("management <>", value, "management");
            return (Criteria) this;
        }

        public Criteria andManagementGreaterThan(String value) {
            addCriterion("management >", value, "management");
            return (Criteria) this;
        }

        public Criteria andManagementGreaterThanOrEqualTo(String value) {
            addCriterion("management >=", value, "management");
            return (Criteria) this;
        }

        public Criteria andManagementLessThan(String value) {
            addCriterion("management <", value, "management");
            return (Criteria) this;
        }

        public Criteria andManagementLessThanOrEqualTo(String value) {
            addCriterion("management <=", value, "management");
            return (Criteria) this;
        }

        public Criteria andManagementLike(String value) {
            addCriterion("management like", value, "management");
            return (Criteria) this;
        }

        public Criteria andManagementNotLike(String value) {
            addCriterion("management not like", value, "management");
            return (Criteria) this;
        }

        public Criteria andManagementIn(List<String> values) {
            addCriterion("management in", values, "management");
            return (Criteria) this;
        }

        public Criteria andManagementNotIn(List<String> values) {
            addCriterion("management not in", values, "management");
            return (Criteria) this;
        }

        public Criteria andManagementBetween(String value1, String value2) {
            addCriterion("management between", value1, value2, "management");
            return (Criteria) this;
        }

        public Criteria andManagementNotBetween(String value1, String value2) {
            addCriterion("management not between", value1, value2, "management");
            return (Criteria) this;
        }

        public Criteria andCustodianIsNull() {
            addCriterion("custodian is null");
            return (Criteria) this;
        }

        public Criteria andCustodianIsNotNull() {
            addCriterion("custodian is not null");
            return (Criteria) this;
        }

        public Criteria andCustodianEqualTo(String value) {
            addCriterion("custodian =", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianNotEqualTo(String value) {
            addCriterion("custodian <>", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianGreaterThan(String value) {
            addCriterion("custodian >", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianGreaterThanOrEqualTo(String value) {
            addCriterion("custodian >=", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianLessThan(String value) {
            addCriterion("custodian <", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianLessThanOrEqualTo(String value) {
            addCriterion("custodian <=", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianLike(String value) {
            addCriterion("custodian like", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianNotLike(String value) {
            addCriterion("custodian not like", value, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianIn(List<String> values) {
            addCriterion("custodian in", values, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianNotIn(List<String> values) {
            addCriterion("custodian not in", values, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianBetween(String value1, String value2) {
            addCriterion("custodian between", value1, value2, "custodian");
            return (Criteria) this;
        }

        public Criteria andCustodianNotBetween(String value1, String value2) {
            addCriterion("custodian not between", value1, value2, "custodian");
            return (Criteria) this;
        }

        public Criteria andFundTypeIsNull() {
            addCriterion("fund_type is null");
            return (Criteria) this;
        }

        public Criteria andFundTypeIsNotNull() {
            addCriterion("fund_type is not null");
            return (Criteria) this;
        }

        public Criteria andFundTypeEqualTo(String value) {
            addCriterion("fund_type =", value, "fundType");
            return (Criteria) this;
        }

        public Criteria andFundTypeNotEqualTo(String value) {
            addCriterion("fund_type <>", value, "fundType");
            return (Criteria) this;
        }

        public Criteria andFundTypeGreaterThan(String value) {
            addCriterion("fund_type >", value, "fundType");
            return (Criteria) this;
        }

        public Criteria andFundTypeGreaterThanOrEqualTo(String value) {
            addCriterion("fund_type >=", value, "fundType");
            return (Criteria) this;
        }

        public Criteria andFundTypeLessThan(String value) {
            addCriterion("fund_type <", value, "fundType");
            return (Criteria) this;
        }

        public Criteria andFundTypeLessThanOrEqualTo(String value) {
            addCriterion("fund_type <=", value, "fundType");
            return (Criteria) this;
        }

        public Criteria andFundTypeLike(String value) {
            addCriterion("fund_type like", value, "fundType");
            return (Criteria) this;
        }

        public Criteria andFundTypeNotLike(String value) {
            addCriterion("fund_type not like", value, "fundType");
            return (Criteria) this;
        }

        public Criteria andFundTypeIn(List<String> values) {
            addCriterion("fund_type in", values, "fundType");
            return (Criteria) this;
        }

        public Criteria andFundTypeNotIn(List<String> values) {
            addCriterion("fund_type not in", values, "fundType");
            return (Criteria) this;
        }

        public Criteria andFundTypeBetween(String value1, String value2) {
            addCriterion("fund_type between", value1, value2, "fundType");
            return (Criteria) this;
        }

        public Criteria andFundTypeNotBetween(String value1, String value2) {
            addCriterion("fund_type not between", value1, value2, "fundType");
            return (Criteria) this;
        }

        public Criteria andFoundDateIsNull() {
            addCriterion("found_date is null");
            return (Criteria) this;
        }

        public Criteria andFoundDateIsNotNull() {
            addCriterion("found_date is not null");
            return (Criteria) this;
        }

        public Criteria andFoundDateEqualTo(String value) {
            addCriterion("found_date =", value, "foundDate");
            return (Criteria) this;
        }

        public Criteria andFoundDateNotEqualTo(String value) {
            addCriterion("found_date <>", value, "foundDate");
            return (Criteria) this;
        }

        public Criteria andFoundDateGreaterThan(String value) {
            addCriterion("found_date >", value, "foundDate");
            return (Criteria) this;
        }

        public Criteria andFoundDateGreaterThanOrEqualTo(String value) {
            addCriterion("found_date >=", value, "foundDate");
            return (Criteria) this;
        }

        public Criteria andFoundDateLessThan(String value) {
            addCriterion("found_date <", value, "foundDate");
            return (Criteria) this;
        }

        public Criteria andFoundDateLessThanOrEqualTo(String value) {
            addCriterion("found_date <=", value, "foundDate");
            return (Criteria) this;
        }

        public Criteria andFoundDateLike(String value) {
            addCriterion("found_date like", value, "foundDate");
            return (Criteria) this;
        }

        public Criteria andFoundDateNotLike(String value) {
            addCriterion("found_date not like", value, "foundDate");
            return (Criteria) this;
        }

        public Criteria andFoundDateIn(List<String> values) {
            addCriterion("found_date in", values, "foundDate");
            return (Criteria) this;
        }

        public Criteria andFoundDateNotIn(List<String> values) {
            addCriterion("found_date not in", values, "foundDate");
            return (Criteria) this;
        }

        public Criteria andFoundDateBetween(String value1, String value2) {
            addCriterion("found_date between", value1, value2, "foundDate");
            return (Criteria) this;
        }

        public Criteria andFoundDateNotBetween(String value1, String value2) {
            addCriterion("found_date not between", value1, value2, "foundDate");
            return (Criteria) this;
        }

        public Criteria andDueDateIsNull() {
            addCriterion("due_date is null");
            return (Criteria) this;
        }

        public Criteria andDueDateIsNotNull() {
            addCriterion("due_date is not null");
            return (Criteria) this;
        }

        public Criteria andDueDateEqualTo(String value) {
            addCriterion("due_date =", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateNotEqualTo(String value) {
            addCriterion("due_date <>", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateGreaterThan(String value) {
            addCriterion("due_date >", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateGreaterThanOrEqualTo(String value) {
            addCriterion("due_date >=", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateLessThan(String value) {
            addCriterion("due_date <", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateLessThanOrEqualTo(String value) {
            addCriterion("due_date <=", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateLike(String value) {
            addCriterion("due_date like", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateNotLike(String value) {
            addCriterion("due_date not like", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateIn(List<String> values) {
            addCriterion("due_date in", values, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateNotIn(List<String> values) {
            addCriterion("due_date not in", values, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateBetween(String value1, String value2) {
            addCriterion("due_date between", value1, value2, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateNotBetween(String value1, String value2) {
            addCriterion("due_date not between", value1, value2, "dueDate");
            return (Criteria) this;
        }

        public Criteria andListDateIsNull() {
            addCriterion("list_date is null");
            return (Criteria) this;
        }

        public Criteria andListDateIsNotNull() {
            addCriterion("list_date is not null");
            return (Criteria) this;
        }

        public Criteria andListDateEqualTo(String value) {
            addCriterion("list_date =", value, "listDate");
            return (Criteria) this;
        }

        public Criteria andListDateNotEqualTo(String value) {
            addCriterion("list_date <>", value, "listDate");
            return (Criteria) this;
        }

        public Criteria andListDateGreaterThan(String value) {
            addCriterion("list_date >", value, "listDate");
            return (Criteria) this;
        }

        public Criteria andListDateGreaterThanOrEqualTo(String value) {
            addCriterion("list_date >=", value, "listDate");
            return (Criteria) this;
        }

        public Criteria andListDateLessThan(String value) {
            addCriterion("list_date <", value, "listDate");
            return (Criteria) this;
        }

        public Criteria andListDateLessThanOrEqualTo(String value) {
            addCriterion("list_date <=", value, "listDate");
            return (Criteria) this;
        }

        public Criteria andListDateLike(String value) {
            addCriterion("list_date like", value, "listDate");
            return (Criteria) this;
        }

        public Criteria andListDateNotLike(String value) {
            addCriterion("list_date not like", value, "listDate");
            return (Criteria) this;
        }

        public Criteria andListDateIn(List<String> values) {
            addCriterion("list_date in", values, "listDate");
            return (Criteria) this;
        }

        public Criteria andListDateNotIn(List<String> values) {
            addCriterion("list_date not in", values, "listDate");
            return (Criteria) this;
        }

        public Criteria andListDateBetween(String value1, String value2) {
            addCriterion("list_date between", value1, value2, "listDate");
            return (Criteria) this;
        }

        public Criteria andListDateNotBetween(String value1, String value2) {
            addCriterion("list_date not between", value1, value2, "listDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateIsNull() {
            addCriterion("issue_date is null");
            return (Criteria) this;
        }

        public Criteria andIssueDateIsNotNull() {
            addCriterion("issue_date is not null");
            return (Criteria) this;
        }

        public Criteria andIssueDateEqualTo(String value) {
            addCriterion("issue_date =", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotEqualTo(String value) {
            addCriterion("issue_date <>", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateGreaterThan(String value) {
            addCriterion("issue_date >", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateGreaterThanOrEqualTo(String value) {
            addCriterion("issue_date >=", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateLessThan(String value) {
            addCriterion("issue_date <", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateLessThanOrEqualTo(String value) {
            addCriterion("issue_date <=", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateLike(String value) {
            addCriterion("issue_date like", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotLike(String value) {
            addCriterion("issue_date not like", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateIn(List<String> values) {
            addCriterion("issue_date in", values, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotIn(List<String> values) {
            addCriterion("issue_date not in", values, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateBetween(String value1, String value2) {
            addCriterion("issue_date between", value1, value2, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotBetween(String value1, String value2) {
            addCriterion("issue_date not between", value1, value2, "issueDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateIsNull() {
            addCriterion("delist_date is null");
            return (Criteria) this;
        }

        public Criteria andDelistDateIsNotNull() {
            addCriterion("delist_date is not null");
            return (Criteria) this;
        }

        public Criteria andDelistDateEqualTo(String value) {
            addCriterion("delist_date =", value, "delistDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateNotEqualTo(String value) {
            addCriterion("delist_date <>", value, "delistDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateGreaterThan(String value) {
            addCriterion("delist_date >", value, "delistDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateGreaterThanOrEqualTo(String value) {
            addCriterion("delist_date >=", value, "delistDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateLessThan(String value) {
            addCriterion("delist_date <", value, "delistDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateLessThanOrEqualTo(String value) {
            addCriterion("delist_date <=", value, "delistDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateLike(String value) {
            addCriterion("delist_date like", value, "delistDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateNotLike(String value) {
            addCriterion("delist_date not like", value, "delistDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateIn(List<String> values) {
            addCriterion("delist_date in", values, "delistDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateNotIn(List<String> values) {
            addCriterion("delist_date not in", values, "delistDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateBetween(String value1, String value2) {
            addCriterion("delist_date between", value1, value2, "delistDate");
            return (Criteria) this;
        }

        public Criteria andDelistDateNotBetween(String value1, String value2) {
            addCriterion("delist_date not between", value1, value2, "delistDate");
            return (Criteria) this;
        }

        public Criteria andIssueAmountIsNull() {
            addCriterion("issue_amount is null");
            return (Criteria) this;
        }

        public Criteria andIssueAmountIsNotNull() {
            addCriterion("issue_amount is not null");
            return (Criteria) this;
        }

        public Criteria andIssueAmountEqualTo(Double value) {
            addCriterion("issue_amount =", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountNotEqualTo(Double value) {
            addCriterion("issue_amount <>", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountGreaterThan(Double value) {
            addCriterion("issue_amount >", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("issue_amount >=", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountLessThan(Double value) {
            addCriterion("issue_amount <", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountLessThanOrEqualTo(Double value) {
            addCriterion("issue_amount <=", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountIn(List<Double> values) {
            addCriterion("issue_amount in", values, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountNotIn(List<Double> values) {
            addCriterion("issue_amount not in", values, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountBetween(Double value1, Double value2) {
            addCriterion("issue_amount between", value1, value2, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountNotBetween(Double value1, Double value2) {
            addCriterion("issue_amount not between", value1, value2, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andMFeeIsNull() {
            addCriterion("m_fee is null");
            return (Criteria) this;
        }

        public Criteria andMFeeIsNotNull() {
            addCriterion("m_fee is not null");
            return (Criteria) this;
        }

        public Criteria andMFeeEqualTo(Double value) {
            addCriterion("m_fee =", value, "mFee");
            return (Criteria) this;
        }

        public Criteria andMFeeNotEqualTo(Double value) {
            addCriterion("m_fee <>", value, "mFee");
            return (Criteria) this;
        }

        public Criteria andMFeeGreaterThan(Double value) {
            addCriterion("m_fee >", value, "mFee");
            return (Criteria) this;
        }

        public Criteria andMFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("m_fee >=", value, "mFee");
            return (Criteria) this;
        }

        public Criteria andMFeeLessThan(Double value) {
            addCriterion("m_fee <", value, "mFee");
            return (Criteria) this;
        }

        public Criteria andMFeeLessThanOrEqualTo(Double value) {
            addCriterion("m_fee <=", value, "mFee");
            return (Criteria) this;
        }

        public Criteria andMFeeIn(List<Double> values) {
            addCriterion("m_fee in", values, "mFee");
            return (Criteria) this;
        }

        public Criteria andMFeeNotIn(List<Double> values) {
            addCriterion("m_fee not in", values, "mFee");
            return (Criteria) this;
        }

        public Criteria andMFeeBetween(Double value1, Double value2) {
            addCriterion("m_fee between", value1, value2, "mFee");
            return (Criteria) this;
        }

        public Criteria andMFeeNotBetween(Double value1, Double value2) {
            addCriterion("m_fee not between", value1, value2, "mFee");
            return (Criteria) this;
        }

        public Criteria andCFeeIsNull() {
            addCriterion("c_fee is null");
            return (Criteria) this;
        }

        public Criteria andCFeeIsNotNull() {
            addCriterion("c_fee is not null");
            return (Criteria) this;
        }

        public Criteria andCFeeEqualTo(Double value) {
            addCriterion("c_fee =", value, "cFee");
            return (Criteria) this;
        }

        public Criteria andCFeeNotEqualTo(Double value) {
            addCriterion("c_fee <>", value, "cFee");
            return (Criteria) this;
        }

        public Criteria andCFeeGreaterThan(Double value) {
            addCriterion("c_fee >", value, "cFee");
            return (Criteria) this;
        }

        public Criteria andCFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("c_fee >=", value, "cFee");
            return (Criteria) this;
        }

        public Criteria andCFeeLessThan(Double value) {
            addCriterion("c_fee <", value, "cFee");
            return (Criteria) this;
        }

        public Criteria andCFeeLessThanOrEqualTo(Double value) {
            addCriterion("c_fee <=", value, "cFee");
            return (Criteria) this;
        }

        public Criteria andCFeeIn(List<Double> values) {
            addCriterion("c_fee in", values, "cFee");
            return (Criteria) this;
        }

        public Criteria andCFeeNotIn(List<Double> values) {
            addCriterion("c_fee not in", values, "cFee");
            return (Criteria) this;
        }

        public Criteria andCFeeBetween(Double value1, Double value2) {
            addCriterion("c_fee between", value1, value2, "cFee");
            return (Criteria) this;
        }

        public Criteria andCFeeNotBetween(Double value1, Double value2) {
            addCriterion("c_fee not between", value1, value2, "cFee");
            return (Criteria) this;
        }

        public Criteria andDurationYearIsNull() {
            addCriterion("duration_year is null");
            return (Criteria) this;
        }

        public Criteria andDurationYearIsNotNull() {
            addCriterion("duration_year is not null");
            return (Criteria) this;
        }

        public Criteria andDurationYearEqualTo(Double value) {
            addCriterion("duration_year =", value, "durationYear");
            return (Criteria) this;
        }

        public Criteria andDurationYearNotEqualTo(Double value) {
            addCriterion("duration_year <>", value, "durationYear");
            return (Criteria) this;
        }

        public Criteria andDurationYearGreaterThan(Double value) {
            addCriterion("duration_year >", value, "durationYear");
            return (Criteria) this;
        }

        public Criteria andDurationYearGreaterThanOrEqualTo(Double value) {
            addCriterion("duration_year >=", value, "durationYear");
            return (Criteria) this;
        }

        public Criteria andDurationYearLessThan(Double value) {
            addCriterion("duration_year <", value, "durationYear");
            return (Criteria) this;
        }

        public Criteria andDurationYearLessThanOrEqualTo(Double value) {
            addCriterion("duration_year <=", value, "durationYear");
            return (Criteria) this;
        }

        public Criteria andDurationYearIn(List<Double> values) {
            addCriterion("duration_year in", values, "durationYear");
            return (Criteria) this;
        }

        public Criteria andDurationYearNotIn(List<Double> values) {
            addCriterion("duration_year not in", values, "durationYear");
            return (Criteria) this;
        }

        public Criteria andDurationYearBetween(Double value1, Double value2) {
            addCriterion("duration_year between", value1, value2, "durationYear");
            return (Criteria) this;
        }

        public Criteria andDurationYearNotBetween(Double value1, Double value2) {
            addCriterion("duration_year not between", value1, value2, "durationYear");
            return (Criteria) this;
        }

        public Criteria andPValueIsNull() {
            addCriterion("p_value is null");
            return (Criteria) this;
        }

        public Criteria andPValueIsNotNull() {
            addCriterion("p_value is not null");
            return (Criteria) this;
        }

        public Criteria andPValueEqualTo(Double value) {
            addCriterion("p_value =", value, "pValue");
            return (Criteria) this;
        }

        public Criteria andPValueNotEqualTo(Double value) {
            addCriterion("p_value <>", value, "pValue");
            return (Criteria) this;
        }

        public Criteria andPValueGreaterThan(Double value) {
            addCriterion("p_value >", value, "pValue");
            return (Criteria) this;
        }

        public Criteria andPValueGreaterThanOrEqualTo(Double value) {
            addCriterion("p_value >=", value, "pValue");
            return (Criteria) this;
        }

        public Criteria andPValueLessThan(Double value) {
            addCriterion("p_value <", value, "pValue");
            return (Criteria) this;
        }

        public Criteria andPValueLessThanOrEqualTo(Double value) {
            addCriterion("p_value <=", value, "pValue");
            return (Criteria) this;
        }

        public Criteria andPValueIn(List<Double> values) {
            addCriterion("p_value in", values, "pValue");
            return (Criteria) this;
        }

        public Criteria andPValueNotIn(List<Double> values) {
            addCriterion("p_value not in", values, "pValue");
            return (Criteria) this;
        }

        public Criteria andPValueBetween(Double value1, Double value2) {
            addCriterion("p_value between", value1, value2, "pValue");
            return (Criteria) this;
        }

        public Criteria andPValueNotBetween(Double value1, Double value2) {
            addCriterion("p_value not between", value1, value2, "pValue");
            return (Criteria) this;
        }

        public Criteria andMinAmountIsNull() {
            addCriterion("min_amount is null");
            return (Criteria) this;
        }

        public Criteria andMinAmountIsNotNull() {
            addCriterion("min_amount is not null");
            return (Criteria) this;
        }

        public Criteria andMinAmountEqualTo(Double value) {
            addCriterion("min_amount =", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountNotEqualTo(Double value) {
            addCriterion("min_amount <>", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountGreaterThan(Double value) {
            addCriterion("min_amount >", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("min_amount >=", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountLessThan(Double value) {
            addCriterion("min_amount <", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountLessThanOrEqualTo(Double value) {
            addCriterion("min_amount <=", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountIn(List<Double> values) {
            addCriterion("min_amount in", values, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountNotIn(List<Double> values) {
            addCriterion("min_amount not in", values, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountBetween(Double value1, Double value2) {
            addCriterion("min_amount between", value1, value2, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountNotBetween(Double value1, Double value2) {
            addCriterion("min_amount not between", value1, value2, "minAmount");
            return (Criteria) this;
        }

        public Criteria andExpReturnIsNull() {
            addCriterion("exp_return is null");
            return (Criteria) this;
        }

        public Criteria andExpReturnIsNotNull() {
            addCriterion("exp_return is not null");
            return (Criteria) this;
        }

        public Criteria andExpReturnEqualTo(String value) {
            addCriterion("exp_return =", value, "expReturn");
            return (Criteria) this;
        }

        public Criteria andExpReturnNotEqualTo(String value) {
            addCriterion("exp_return <>", value, "expReturn");
            return (Criteria) this;
        }

        public Criteria andExpReturnGreaterThan(String value) {
            addCriterion("exp_return >", value, "expReturn");
            return (Criteria) this;
        }

        public Criteria andExpReturnGreaterThanOrEqualTo(String value) {
            addCriterion("exp_return >=", value, "expReturn");
            return (Criteria) this;
        }

        public Criteria andExpReturnLessThan(String value) {
            addCriterion("exp_return <", value, "expReturn");
            return (Criteria) this;
        }

        public Criteria andExpReturnLessThanOrEqualTo(String value) {
            addCriterion("exp_return <=", value, "expReturn");
            return (Criteria) this;
        }

        public Criteria andExpReturnLike(String value) {
            addCriterion("exp_return like", value, "expReturn");
            return (Criteria) this;
        }

        public Criteria andExpReturnNotLike(String value) {
            addCriterion("exp_return not like", value, "expReturn");
            return (Criteria) this;
        }

        public Criteria andExpReturnIn(List<String> values) {
            addCriterion("exp_return in", values, "expReturn");
            return (Criteria) this;
        }

        public Criteria andExpReturnNotIn(List<String> values) {
            addCriterion("exp_return not in", values, "expReturn");
            return (Criteria) this;
        }

        public Criteria andExpReturnBetween(String value1, String value2) {
            addCriterion("exp_return between", value1, value2, "expReturn");
            return (Criteria) this;
        }

        public Criteria andExpReturnNotBetween(String value1, String value2) {
            addCriterion("exp_return not between", value1, value2, "expReturn");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andInvestTypeIsNull() {
            addCriterion("invest_type is null");
            return (Criteria) this;
        }

        public Criteria andInvestTypeIsNotNull() {
            addCriterion("invest_type is not null");
            return (Criteria) this;
        }

        public Criteria andInvestTypeEqualTo(String value) {
            addCriterion("invest_type =", value, "investType");
            return (Criteria) this;
        }

        public Criteria andInvestTypeNotEqualTo(String value) {
            addCriterion("invest_type <>", value, "investType");
            return (Criteria) this;
        }

        public Criteria andInvestTypeGreaterThan(String value) {
            addCriterion("invest_type >", value, "investType");
            return (Criteria) this;
        }

        public Criteria andInvestTypeGreaterThanOrEqualTo(String value) {
            addCriterion("invest_type >=", value, "investType");
            return (Criteria) this;
        }

        public Criteria andInvestTypeLessThan(String value) {
            addCriterion("invest_type <", value, "investType");
            return (Criteria) this;
        }

        public Criteria andInvestTypeLessThanOrEqualTo(String value) {
            addCriterion("invest_type <=", value, "investType");
            return (Criteria) this;
        }

        public Criteria andInvestTypeLike(String value) {
            addCriterion("invest_type like", value, "investType");
            return (Criteria) this;
        }

        public Criteria andInvestTypeNotLike(String value) {
            addCriterion("invest_type not like", value, "investType");
            return (Criteria) this;
        }

        public Criteria andInvestTypeIn(List<String> values) {
            addCriterion("invest_type in", values, "investType");
            return (Criteria) this;
        }

        public Criteria andInvestTypeNotIn(List<String> values) {
            addCriterion("invest_type not in", values, "investType");
            return (Criteria) this;
        }

        public Criteria andInvestTypeBetween(String value1, String value2) {
            addCriterion("invest_type between", value1, value2, "investType");
            return (Criteria) this;
        }

        public Criteria andInvestTypeNotBetween(String value1, String value2) {
            addCriterion("invest_type not between", value1, value2, "investType");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTrusteeIsNull() {
            addCriterion("trustee is null");
            return (Criteria) this;
        }

        public Criteria andTrusteeIsNotNull() {
            addCriterion("trustee is not null");
            return (Criteria) this;
        }

        public Criteria andTrusteeEqualTo(String value) {
            addCriterion("trustee =", value, "trustee");
            return (Criteria) this;
        }

        public Criteria andTrusteeNotEqualTo(String value) {
            addCriterion("trustee <>", value, "trustee");
            return (Criteria) this;
        }

        public Criteria andTrusteeGreaterThan(String value) {
            addCriterion("trustee >", value, "trustee");
            return (Criteria) this;
        }

        public Criteria andTrusteeGreaterThanOrEqualTo(String value) {
            addCriterion("trustee >=", value, "trustee");
            return (Criteria) this;
        }

        public Criteria andTrusteeLessThan(String value) {
            addCriterion("trustee <", value, "trustee");
            return (Criteria) this;
        }

        public Criteria andTrusteeLessThanOrEqualTo(String value) {
            addCriterion("trustee <=", value, "trustee");
            return (Criteria) this;
        }

        public Criteria andTrusteeLike(String value) {
            addCriterion("trustee like", value, "trustee");
            return (Criteria) this;
        }

        public Criteria andTrusteeNotLike(String value) {
            addCriterion("trustee not like", value, "trustee");
            return (Criteria) this;
        }

        public Criteria andTrusteeIn(List<String> values) {
            addCriterion("trustee in", values, "trustee");
            return (Criteria) this;
        }

        public Criteria andTrusteeNotIn(List<String> values) {
            addCriterion("trustee not in", values, "trustee");
            return (Criteria) this;
        }

        public Criteria andTrusteeBetween(String value1, String value2) {
            addCriterion("trustee between", value1, value2, "trustee");
            return (Criteria) this;
        }

        public Criteria andTrusteeNotBetween(String value1, String value2) {
            addCriterion("trustee not between", value1, value2, "trustee");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateIsNull() {
            addCriterion("purc_startdate is null");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateIsNotNull() {
            addCriterion("purc_startdate is not null");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateEqualTo(String value) {
            addCriterion("purc_startdate =", value, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateNotEqualTo(String value) {
            addCriterion("purc_startdate <>", value, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateGreaterThan(String value) {
            addCriterion("purc_startdate >", value, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateGreaterThanOrEqualTo(String value) {
            addCriterion("purc_startdate >=", value, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateLessThan(String value) {
            addCriterion("purc_startdate <", value, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateLessThanOrEqualTo(String value) {
            addCriterion("purc_startdate <=", value, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateLike(String value) {
            addCriterion("purc_startdate like", value, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateNotLike(String value) {
            addCriterion("purc_startdate not like", value, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateIn(List<String> values) {
            addCriterion("purc_startdate in", values, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateNotIn(List<String> values) {
            addCriterion("purc_startdate not in", values, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateBetween(String value1, String value2) {
            addCriterion("purc_startdate between", value1, value2, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andPurcStartdateNotBetween(String value1, String value2) {
            addCriterion("purc_startdate not between", value1, value2, "purcStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateIsNull() {
            addCriterion("redm_startdate is null");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateIsNotNull() {
            addCriterion("redm_startdate is not null");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateEqualTo(String value) {
            addCriterion("redm_startdate =", value, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateNotEqualTo(String value) {
            addCriterion("redm_startdate <>", value, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateGreaterThan(String value) {
            addCriterion("redm_startdate >", value, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateGreaterThanOrEqualTo(String value) {
            addCriterion("redm_startdate >=", value, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateLessThan(String value) {
            addCriterion("redm_startdate <", value, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateLessThanOrEqualTo(String value) {
            addCriterion("redm_startdate <=", value, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateLike(String value) {
            addCriterion("redm_startdate like", value, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateNotLike(String value) {
            addCriterion("redm_startdate not like", value, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateIn(List<String> values) {
            addCriterion("redm_startdate in", values, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateNotIn(List<String> values) {
            addCriterion("redm_startdate not in", values, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateBetween(String value1, String value2) {
            addCriterion("redm_startdate between", value1, value2, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andRedmStartdateNotBetween(String value1, String value2) {
            addCriterion("redm_startdate not between", value1, value2, "redmStartdate");
            return (Criteria) this;
        }

        public Criteria andMarketIsNull() {
            addCriterion("market is null");
            return (Criteria) this;
        }

        public Criteria andMarketIsNotNull() {
            addCriterion("market is not null");
            return (Criteria) this;
        }

        public Criteria andMarketEqualTo(String value) {
            addCriterion("market =", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotEqualTo(String value) {
            addCriterion("market <>", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketGreaterThan(String value) {
            addCriterion("market >", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketGreaterThanOrEqualTo(String value) {
            addCriterion("market >=", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketLessThan(String value) {
            addCriterion("market <", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketLessThanOrEqualTo(String value) {
            addCriterion("market <=", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketLike(String value) {
            addCriterion("market like", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotLike(String value) {
            addCriterion("market not like", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketIn(List<String> values) {
            addCriterion("market in", values, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotIn(List<String> values) {
            addCriterion("market not in", values, "market");
            return (Criteria) this;
        }

        public Criteria andMarketBetween(String value1, String value2) {
            addCriterion("market between", value1, value2, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotBetween(String value1, String value2) {
            addCriterion("market not between", value1, value2, "market");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_data
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 11 15:21:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_data
     *
     * @mbg.generated Thu Jul 11 15:21:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}