package com.tan.start.entity;

import java.util.Date;

public class SuccessRecord extends SuccessRecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_record.state
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_record.create_time
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_record.state
     *
     * @return the value of success_record.state
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_record.state
     *
     * @param state the value for success_record.state
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_record.create_time
     *
     * @return the value of success_record.create_time
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_record.create_time
     *
     * @param createTime the value for success_record.create_time
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}