package com.tan.start.entity;

public class SuccessRecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_record.activity_id
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_record.user_phone
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    private Long userPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_record.activity_id
     *
     * @return the value of success_record.activity_id
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_record.activity_id
     *
     * @param activityId the value for success_record.activity_id
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_record.user_phone
     *
     * @return the value of success_record.user_phone
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public Long getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_record.user_phone
     *
     * @param userPhone the value for success_record.user_phone
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public void setUserPhone(Long userPhone) {
        this.userPhone = userPhone;
    }
}