package com.tan.start.entity;

import java.io.Serializable;

public class SysPermissionGroups implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission_groups.id
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission_groups.value
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission_groups.descrpition
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    private String descrpition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission_groups.id
     *
     * @return the value of sys_permission_groups.id
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission_groups.id
     *
     * @param id the value for sys_permission_groups.id
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission_groups.value
     *
     * @return the value of sys_permission_groups.value
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission_groups.value
     *
     * @param value the value for sys_permission_groups.value
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission_groups.descrpition
     *
     * @return the value of sys_permission_groups.descrpition
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    public String getDescrpition() {
        return descrpition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission_groups.descrpition
     *
     * @param descrpition the value for sys_permission_groups.descrpition
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    public void setDescrpition(String descrpition) {
        this.descrpition = descrpition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", value=").append(value);
        sb.append(", descrpition=").append(descrpition);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysPermissionGroups other = (SysPermissionGroups) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getDescrpition() == null ? other.getDescrpition() == null : this.getDescrpition().equals(other.getDescrpition()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_groups
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getDescrpition() == null) ? 0 : getDescrpition().hashCode());
        return result;
    }
}