package com.tan.start.entity;

import java.io.Serializable;

public class SysPermissionGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission_group.id
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission_group.value
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission_group.descripition
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    private String descripition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_permission_group
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission_group.id
     *
     * @return the value of sys_permission_group.id
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission_group.id
     *
     * @param id the value for sys_permission_group.id
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission_group.value
     *
     * @return the value of sys_permission_group.value
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission_group.value
     *
     * @param value the value for sys_permission_group.value
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission_group.descripition
     *
     * @return the value of sys_permission_group.descripition
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    public String getDescripition() {
        return descripition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission_group.descripition
     *
     * @param descripition the value for sys_permission_group.descripition
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    public void setDescripition(String descripition) {
        this.descripition = descripition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", value=").append(value);
        sb.append(", descripition=").append(descripition);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysPermissionGroup other = (SysPermissionGroup) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getDescripition() == null ? other.getDescripition() == null : this.getDescripition().equals(other.getDescripition()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_group
     *
     * @mbg.generated Fri Jul 12 21:30:54 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getDescripition() == null) ? 0 : getDescripition().hashCode());
        return result;
    }
}