package com.tan.start.entity;

import java.io.Serializable;

public class SysPermissionResourcesKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission_resources.permission_id
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission_resources.resources_id
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    private Long resourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_permission_resources
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission_resources.permission_id
     *
     * @return the value of sys_permission_resources.permission_id
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission_resources.permission_id
     *
     * @param permissionId the value for sys_permission_resources.permission_id
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission_resources.resources_id
     *
     * @return the value of sys_permission_resources.resources_id
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    public Long getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission_resources.resources_id
     *
     * @param resourcesId the value for sys_permission_resources.resources_id
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    public void setResourcesId(Long resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resources
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", permissionId=").append(permissionId);
        sb.append(", resourcesId=").append(resourcesId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resources
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysPermissionResourcesKey other = (SysPermissionResourcesKey) that;
        return (this.getPermissionId() == null ? other.getPermissionId() == null : this.getPermissionId().equals(other.getPermissionId()))
            && (this.getResourcesId() == null ? other.getResourcesId() == null : this.getResourcesId().equals(other.getResourcesId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_resources
     *
     * @mbg.generated Wed Apr 10 15:27:59 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPermissionId() == null) ? 0 : getPermissionId().hashCode());
        result = prime * result + ((getResourcesId() == null) ? 0 : getResourcesId().hashCode());
        return result;
    }
}