package com.tan.start.entity;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.uname
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.unumber
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    private Integer unumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.uname
     *
     * @return the value of user_info.uname
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.uname
     *
     * @param uname the value for user_info.uname
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.unumber
     *
     * @return the value of user_info.unumber
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public Integer getUnumber() {
        return unumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.unumber
     *
     * @param unumber the value for user_info.unumber
     *
     * @mbg.generated Sat Mar 09 09:53:11 CST 2019
     */
    public void setUnumber(Integer unumber) {
        this.unumber = unumber;
    }
}